### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by ghost** [HostsTools/Windows-python#1]
依照国内的网络环境 请妥善使用release功能 尽可能不要将bin文件放在repo中
这样fork代码的时候会加重网络的负担

另: 文章404 不知是什么原因

**Comment by guoruibiao** [comment]
谢谢您的建议 :+1: 
博客404是被CSDN官方强制删除的，包含翻墙等敏感词导致，现已更新。

**Comment by ghost** [comment]
→_→
您可以研究一下pull request的使用方法  然后在原项目修改 再反pr回来

**Comment by guoruibiao** [comment]
O(∩_∩)O谢谢
