### ISSUE TITLE
我发现这个工具有点小问题

### ISSUE THREAD

**Issue by theratlesnake** [HostsTools/Windows-python#3]
我第一次运行的时候，我的hosts文件是空的，运行后，把空的复制到了hosts_bak，然后第二次运行这个软件，这个hosts_bak被修改了，最初空的变成了第一次时产生的hosts数据了，也就是默认备份的上一次的数据，这样是不是有点问题？

**Comment by Too-Naive** [comment]
备份会连续保留至少20个版本 您仔细看看文件夹肯定还有其他的备份版本存在
感谢使用

**Comment by ghost** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)看错程序了= =

**Comment by theratlesnake** [comment]
？？一脸懵逼，你在说啥

**Comment by ghost** [comment]
看错项目了抱歉= =

**Comment by guoruibiao** [comment]
@theratlesnake 你觉得做成什么样的效果好呢？
这个默认备份的原理就是这样啦，有好的思路不妨谈一谈哈

**Comment by theratlesnake** [comment]
@guoruibiao 其实我很多东西不懂，随口反馈一下的哈，另外，请问一下，youtube可以打开，视频播放不了，有什么方法可以看吗？

**Comment by guoruibiao** [comment]
@theratlesnake 更改hosts文件内容做到的翻墙其实还是很鸡肋的，毕竟不能全网ip覆盖，原因你应该懂的啦。

**Comment by theratlesnake** [comment]
@guoruibiao  说实话，我不懂

**Comment by Leeson0202** [comment]
翻墙了 然后怎么不翻墙呢

**Comment by guoruibiao** [comment]
> 翻墙了 然后怎么不翻墙呢

被 ban 了吧
